package dsm

object DsmAgentHelpText {
    fun generate(): String = buildString {
        appendLine("=== DSM (Dependency Structure Matrix): AI Agent Guide ===")
        appendLine()
        appendLine("DSM is a Gradle plugin that analyzes JVM bytecode to produce a package")
        appendLine("dependency matrix. It helps you understand, verify, and improve the")
        appendLine("architecture of a codebase.")
        appendLine()
        appendLine("--- Why use a DSM? ---")
        appendLine()
        appendLine("You lack the implicit architectural understanding that human developers")
        appendLine("accumulate over time. You can read individual files, but you have no")
        appendLine("birds-eye view of the dependency structure. A DSM fills that gap:")
        appendLine()
        appendLine("- See which packages depend on which, and how strongly (reference counts).")
        appendLine("- Detect cyclic dependencies immediately — they show as cells above the diagonal.")
        appendLine("- Verify refactoring results: run DSM before and after to confirm you didn't")
        appendLine("  introduce new cycles or increase coupling.")
        appendLine()
        appendLine("--- Recommended Workflow ---")
        appendLine()
        appendLine("1. BASELINE: Run DSM before making changes")
        appendLine("   ./gradlew dsm")
        appendLine()
        appendLine("2. WORK: Make your changes (feature, refactoring, etc.)")
        appendLine()
        appendLine("3. VERIFY: Run DSM again and compare")
        appendLine("   ./gradlew dsm")
        appendLine("   # Check: no new cyclic dependencies? Coupling not increased?")
        appendLine()
        appendLine("--- Task Reference ---")
        appendLine()
        appendLine("  dsm                       Generate the dependency structure matrix")
        appendLine()
        appendLine("--- Parameters ---")
        appendLine()
        appendLine("  Extension block (build.gradle.kts):")
        appendLine("    dsm {")
        appendLine("        rootPackage.set(\"com.example\")   // Scope to a package prefix (default: all)")
        appendLine("        depth.set(2)                      // Package segments to group by (default: 2)")
        appendLine("        classesDir.set(...)               // Classes directory (default: build/classes/kotlin/main)")
        appendLine("        htmlOutputFile.set(...)           // Optional HTML report output path")
        appendLine("    }")
        appendLine()
        appendLine("  Command-line overrides:")
        appendLine("    -Pdsm.depth=3                         // Override depth without editing build file")
        appendLine("    -Pdsm.html=build/reports/dsm.html     // Generate HTML report")
        appendLine()
        appendLine("--- Reading the Matrix ---")
        appendLine()
        appendLine("The matrix is read as: row depends on column.")
        appendLine("Cell values are the number of dependency references.")
        appendLine()
        appendLine("  - Cells below the diagonal = forward dependencies (expected, good)")
        appendLine("  - Cells above the diagonal = backward dependencies (potential cycles, review these)")
        appendLine()
        appendLine("Example output:")
        appendLine()
        appendLine("  Legend:")
        appendLine("      1: api")
        appendLine("      2: core")
        appendLine("      3: persistence")
        appendLine()
        appendLine("                       1   2   3")
        appendLine("  ---------------------------------")
        appendLine("    1. api             .       2")
        appendLine("    2. core            3   .")
        appendLine("    3. persistence     1   4   .")
        appendLine()
        appendLine("Here, api depends on persistence (2 refs, above diagonal = backward, review!).")
        appendLine("persistence depends on core (4 refs, below diagonal = forward, expected).")
        appendLine()
        appendLine("When cycles are detected, the output lists the specific class-level edges:")
        appendLine("  WARNING: Cyclic dependencies detected:")
        appendLine("    api <-> persistence  (2 refs / 1 refs)")
        appendLine("      api.UserController -> persistence.UserRepository")
        appendLine("      persistence.AuditLogger -> api.RequestContext")
        appendLine()
        appendLine("--- Tips for Optimal Results ---")
        appendLine()
        appendLine("- Set rootPackage to your project's base package to filter out noise from")
        appendLine("  third-party libraries.")
        appendLine("- Increase depth when you need finer-grained analysis (e.g. depth=3 to see")
        appendLine("  sub-packages within a module).")
        appendLine("- Use the HTML report (-Pdsm.html=...) when you need to present results")
        appendLine("  to a human — it has color-coded cells and hover tooltips.")
        appendLine("- Run DSM as a pre/post check around any architectural refactoring.")
        appendLine("- The DSM depends on the `classes` task, so bytecode is compiled automatically.")
    }
}
